name: Build Wheels

on:
  push:
    branches: [ lets_package ]
  workflow_dispatch: 
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - run: python -m build
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: dist/*

  combine-artifacts:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: ./all-wheels
      - uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: ./all-wheels
