name: Build Wheels

on:
  push:
    branches: [ lets_package ]
  workflow_dispatch: 
  pull_request:

jobs:
  build_wheels:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install cibuildwheel
        run: pip install cibuildwheel==2.*
      - name: Build wheels
        run: cibuildwheel --output-dir dist
      - name: Upload wheels as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: dist/*.whl
